### ISSUE TITLE
Error Code 1: Cuda Runtime (misaligned address)

### ISSUE THREAD

**Issue by whuhit** [spacewalk01/yolov9-bytetrack-tensorrt#4]
When I run it, the following error occurs. Could you please help me take a look?

![image](https://github.com/spacewalk01/yolov9-bytetrack-tensorrt/assets/22534064/9e32db66-06d0-4922-92de-0e9b08fbe687)

**Comment by spacewalk01** [comment]
Looks the error occurs when destroying stream (error line yolov9.cpp : 71, 74). I added cuda sync before destroying cuda stream. You try again.

https://github.com/spacewalk01/TensorRT-YOLOv9/blob/849ae2366f191c3ebb74bbd88464015aa3d0abb6/src/yolov9.cpp#L71

**Comment by whuhit** [comment]
> Looks the error occurs when destroying stream (error line yolov9.cpp : 71, 74). I added cuda sync before destroying cuda stream. You may try it again.
> 
> https://github.com/spacewalk01/TensorRT-YOLOv9/blob/849ae2366f191c3ebb74bbd88464015aa3d0abb6/src/yolov9.cpp#L71

I tried, but it didn't work. My cuda version is 11.6, tensorrt is 8.6.1.6, eigen is 3.4.0，opencv is 4.5.2，could you share your envs? and this is my onnx file，is it correct?  [link](https://pan.baidu.com/s/1Bn3KXrP-gjoCG_kG1IAhbQ?pwd=3h3l )

**Comment by spacewalk01** [comment]
My env was:
- TensorRT-8.6.0.12
- opencv 4.9
- cdua 11.8
- eigen 3.4

**Comment by whuhit** [comment]
> My env was:
> 
> * TensorRT-8.6.0.12
> * opencv 4.9
> * cdua 11.8
> * eigen 3.4.0

I changed back to your old [TensorRT-YOLOv9](https://github.com/spacewalk01/TensorRT-YOLOv9) version without preprocess.cu，and use yolov9-c.pt(not yolov9-c-converted.pt), that works for me.

**Comment by spacewalk01** [comment]
That is great. The old version preprocesses the input image on cpu

**Comment by spacewalk01** [comment]
I will add the old version as a branch. Thank you for reporting it!

**Comment by spacewalk01** [comment]
https://github.com/spacewalk01/TensorRT-YOLOv9/tree/cpu_preprocessing
